image: node:9.11.2

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

build:
  only:
    - master
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - build/

deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ls -R ./build
    - ls -R ./api
    - scp -rp ./build/* patjennings@92.139.41.114:/var/www/timetracker.thomasguesnon.net
    - scp -rp ./api patjennings@92.139.41.114:/var/www/timetracker.thomasguesnon.net
    - scp -rp ./package.json patjennings@92.139.41.114:/var/www/timetracker.thomasguesnon.net
    - ssh patjennings@92.139.41.114 && cd /var/www/timetracker.thomasguesnon.net && npm install

  only:
    - master
