image: node:9.11.2

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

build:
  only:
    - master
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - npm run stage
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - build-production/
    - build-staging/

deploy:
  stage: deploy
  dependencies:
    - build-production
    - build-staging
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - cp ./api ./build-production
    - cp conf.js ./build-production
    - cp ./api ./build-staging
    - cp conf.js ./build-staging
    - scp -rp ./build-production/* "$USER"@"$HOST":/var/www/time.thomasguesnon.net
    - scp -rp ./build-staging/* "$USER"@"$HOST":/var/www/pisteurdetemps.thomasguesnon.net
    - scp -rp ./package.json "$USER"@"$HOST":/var/www/time.thomasguesnon.net
    
  only:
    - master
